# Site settings
title: Npgsql
subtitle: ".NET Data Provider for PostgreSQL"
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

#baseurl: ""
#url: "http://www.npgsql.org"
baseurl: "/npgsql/"
url: "http://npgsql.github.io"
permalink:   /:categories/:title/

twitter_username: jekyllrb
github_username:  jekyll

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-56130753-1

# Build settings
markdown: kramdown
